stages:
  preprocess:
    cmd: python3 get_data.py
    deps:
    - get_data.py
    - jigsaw.csv
    outs:
    - cleaned.csv
  train:
    cmd: python3 train.py
    deps:
    - train.py
    - cleaned.csv
    outs:
    - report.txt
    metrics:
    - metrics.json:
        cache: false
